# schema.yml

version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: dataset de données brutes Greenweez

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: liste des ventes Greenweez
        columns:
          - name: date_date
            description: date d'achat
          - name: orders_id
            description: id de la commande 
          - name: pdt_id
            description: id du produit
          - name: revenue
            description: chiffre d'affaires de la commande
          - name: quantity
            description: quantité vendue
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day }

      - name: product
        identifier: raw_gz_product
        description: liste des produits avec prix d'achat Greenweez 
        columns:
          - name: products_id
            description: id du produit
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: prix du produit

      - name: ship
        identifier: raw_gz_ship 
        description: liste des commandes expédiées Greenweez
        columns:
          - name: orders_id
            description: id de la commande
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: frais de ports
          - name: shipping_fee_1
            description: frais de ports doublon
          - name: logCost
            description: coûts logistiques
          - name: ship_cost
            description: coûts de transport

      - name: adwords
        identifier: raw_gz_adwords
        description: performances des campagnes ads
        columns:
          - name: date_date
            description: date de la camapgne
          - name: paid_source
            description: source de la campagne
          - name: campaign_key
            description: ID de la campagne
          - name: campgn_name
            description: nom de la campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'affichage de la campagne
          - name: clicks
            description: nombre de clics de la campagne
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      
      - name: bing
        identifier: raw_gz_bing
        description: performances des campagnes bing
        columns:
          - name: date_date
            description: date de la camapgne
          - name: paid_source
            description: source de la campagne
          - name: campaign_key
            description: ID de la campagne
          - name: campgn_name
            description: nom de la campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'affichage de la campagne
          - name: clicks
            description: nombre de clics de la campagne
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"

      - name: criteo
        identifier: raw_gz_criteo
        description: performances des campagnes criteo
        columns:
          - name: date_date
            description: date de la camapgne
          - name: paid_source
            description: source de la campagne
          - name: campaign_key
            description: ID de la campagne
          - name: campgn_name
            description: nom de la campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'affichage de la campagne
          - name: clicks
            description: nombre de clics de la campagne
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"

      - name: facebook
        identifier: raw_gz_facebook
        description: performances des campagnes facebook
        columns:
          - name: date_date
            description: date de la camapgne
          - name: paid_source
            description: source de la campagne
          - name: campaign_key
            description: ID de la campagne
          - name: campgn_name
            description: nom de la campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'affichage de la campagne
          - name: clicks
            description: nombre de clics de la campagne
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"


models: 
  - name: int_sales_margin
    description : fusion des tables sales et products, calcul marge et coût d'achat, groupée par date, order_id
    columns:
      - name: date_date 
        description: date d'achat
      - name: order_id 
        description: numéro de la commande
      - name: revenue
        description: montant de la commande
      - name: quantity
        description: nombre de produits dans la commande
      - name: purchase_cost
        description: coût d'achat, prix d'achat multiplié par la quantité
      - name: margin
        description: marge, chiffre d'affaires - coûts d'achats

  - name: int_order_operationnal
    description: fusion des tables int_sales_margin et ship, calcul de la marge opérationnelle
    columns: 
      - name: date_date
        description: date d'achat
      - name: orders_id
        description: numéro de commande
      - name: revenue
        description: montant de la commande
      - name: quantity
        description: nombre de produits dans la commande
      - name: purchase_cost
        description: coût d'achat, prix d'achat multiplié par la quantité
      - name: margin
        description: marge, chiffre d'affaires - coûts d'achats
      - name: operationnal_margin,
        description: marge en intégrant les frais de ports et coûts logistiques
      - name: shipping_fee,
        description: frais de transport
      - name: logcost,
        description: coûts de logistique
      - name: ship_cost
        description: coûts d'expédition

  - name: int_campaign
    description: concaténation des 4 sources (ads, bing, criteo, facebook)
    columns:
      - name: date_date
        description: date de la camapgne
      - name: paid_source
        description: source de la campagne
      - name: campaign_key
        description: ID de la campagne
      - name: campgn_name
        description: nom de la campagne
      - name: ads_cost
        description: coût de la campagne
      - name: impression
        description: nombre d'affichage de la campagne
      - name: clicks
        description: nombre de clics de la campagne
    tests:
      - unique:
          column_name: "(date_date || '_' || campaign_key)"
        
  - name: int_campaigns_day
    description: aggrégation de int_campaign par date
    columns:
      - name: date_date
        description: date d'affichage de la campagne
        tests:
          - unique
          - not_null
      - name: ads_costs
        description: coût de la campagne
        tests:
          - not_null
      - name: ads_impressions
        description: nombre d'affichages de la campagne
        tests:
          - not_null
      - name: ads_clicks
        description: nombre de clics de la campagne
        tests:
          - not_null

  - name: finance_campaign_date
    description: table des KPIs pour la finance
    columns:
      - name: date_date
        description: date, clé primaire
        tests:
          - unique
          - not_null
      - name: ads_margin
        description: marge après ajout coûts Ads
      - name: average_basket
        description: panier moyen
      - name: operationnal_margin
        description: marge moins flux logistiques
      - name: ads_costs
        description: coûts Ads
      - name: ads_impressions
        description: total impressions Ads
      - name: ads_clicks
        description: total clics Ads
      - name: nb_transactions
        description: nombre de commandes passées
      - name: quantity
        description: nombre de produits vendus
      - name: revenue
        description: chiffre d'affaires généré
      - name: purchase_cost
        description: prix d'achat
      - name: margin
        description: marge brute
      - name: shipping_fee
        description: frais de ports
      - name: logcost
        description: frais logistiques
